# Generated by Django 3.1.1 on 2020-10-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='optional_text',
            field=models.CharField(default='PLACEHOLDER', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
