# Generated by Django 3.1.1 on 2020-10-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0002_auto_20201013_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='optional_text',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
