# Generated by Django 3.1.1 on 2020-10-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0004_auto_20201013_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/')),
                ('optional_text', models.CharField(blank=True, default='PLACEHOLDER', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
