# Generated by Django 3.1.1 on 2020-10-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0005_auto_20201013_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='ending_timestamp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='videofile',
            name='starting_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
