# Generated by Django 3.1.1 on 2020-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0006_auto_20201014_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='grayscale_option',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
