# Generated by Django 3.1.1 on 2020-10-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0007_videofile_grayscale_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='flipX_option',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='videofile',
            name='flipY_option',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
