# Generated by Django 3.1.1 on 2020-10-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0008_auto_20201019_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='pencil_sketched_option',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
