# Generated by Django 3.1.1 on 2020-10-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0009_videofile_pencil_sketched_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='docfile',
        ),
        migrations.AddField(
            model_name='videofile',
            name='youtube_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
