# Generated by Django 3.1.1 on 2020-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0010_auto_20201024_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='videofile',
            name='docfile',
            field=models.FileField(default='.txt', upload_to='documents/'),
        ),
    ]
