# Generated by Django 3.1.1 on 2020-10-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0011_auto_20201024_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='docfile',
            field=models.FileField(default='.mp4', upload_to='documents/'),
        ),
    ]
